### ISSUE TITLE
v0.9.0-rc* issues

### ISSUE THREAD

**Issue by indexzero** [vowsjs/vows#330]
Please post any issues you have with `vows@0.9.0-rc1` here. It will not be installed as "latest" automatically yet. You will need to install it explicitly:

```
npm install -g vows@next
npm install vows@next
```

Or put the explicit version in your package.json:

``` js
{
  // other properties
  "devDependencies": {
    "vows": "0.9.0-rc1"
  }
}
```

the goal is to release `0.9.0` before the end of next week so please let us know if you have any problems with the release. There are some pretty big changes in there which are documented [in the changelog.](https://github.com/vowsjs/vows/blob/master/CHANGELOG.md#v090-rc1--wed-3-dec-2014) This is an important step to shipping `1.0.0` with some big wins so we appreciate your help!
##### Aside: known OSS modules to assure work
- [ ] foreverjs/forever
- [ ] foreverjs/forever-monitor
- [ ] flatiron/winston
- [ ] flatiron/nconf

**Comment by indexzero** [comment]
@silkentrance these have been fixed. Thanks for your contributions!

**Comment by markstos** [comment]
Since all the issues reported with the 0.9.0 release have been fixed here and there have been further  comments on it in over a eyar, could it be released now?

0.9.0 would fix a deprecation warning that's currently happening when using `vows -v` with 0.8.1 run with Node.js 4.4.2. The warning is:

      util.print is deprecated. Use console.log instead.

This issue has already been fixed in latest code on Github.

**Comment by evanp** [comment]
We ended up going in a different direction, so I'm closing this omnibus issue
